In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
type(arr)



numpy.ndarray

In [4]:
arr.ndim

1

In [5]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
arr2d.ndim

2

In [7]:
arr2d.size

12

In [8]:
arr.size

4

In [9]:
arr.shape

(4,)

In [10]:
arr2d.shape

(4, 3)

In [11]:
arr2d.dtype

dtype('int32')

In [12]:
arr_one = np.zeros(5, int)
print(arr_one)

[0 0 0 0 0]


In [13]:
arr1 = np.empty((3,2))
print(arr1) 

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
np.linspace(1,5,213)

array([1.        , 1.01886792, 1.03773585, 1.05660377, 1.0754717 ,
       1.09433962, 1.11320755, 1.13207547, 1.1509434 , 1.16981132,
       1.18867925, 1.20754717, 1.22641509, 1.24528302, 1.26415094,
       1.28301887, 1.30188679, 1.32075472, 1.33962264, 1.35849057,
       1.37735849, 1.39622642, 1.41509434, 1.43396226, 1.45283019,
       1.47169811, 1.49056604, 1.50943396, 1.52830189, 1.54716981,
       1.56603774, 1.58490566, 1.60377358, 1.62264151, 1.64150943,
       1.66037736, 1.67924528, 1.69811321, 1.71698113, 1.73584906,
       1.75471698, 1.77358491, 1.79245283, 1.81132075, 1.83018868,
       1.8490566 , 1.86792453, 1.88679245, 1.90566038, 1.9245283 ,
       1.94339623, 1.96226415, 1.98113208, 2.        , 2.01886792,
       2.03773585, 2.05660377, 2.0754717 , 2.09433962, 2.11320755,
       2.13207547, 2.1509434 , 2.16981132, 2.18867925, 2.20754717,
       2.22641509, 2.24528302, 2.26415094, 2.28301887, 2.30188679,
       2.32075472, 2.33962264, 2.35849057, 2.37735849, 2.39622

In [15]:
arr2d.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
ar = np.arange(1,15).reshape(2,7)
print(ar)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
ar.transpose()

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13],
       [ 7, 14]])

In [19]:
arr = np.arange(1,10).reshape(3,3)
arr1 = np.arange(14,23).reshape(3,3)

In [20]:
arr + arr1

array([[15, 17, 19],
       [21, 23, 25],
       [27, 29, 31]])

In [21]:
np.add(arr,arr1)

array([[15, 17, 19],
       [21, 23, 25],
       [27, 29, 31]])

In [22]:
arr - arr1

array([[-13, -13, -13],
       [-13, -13, -13],
       [-13, -13, -13]])

In [23]:
np.subtract(arr,arr1)

array([[-13, -13, -13],
       [-13, -13, -13],
       [-13, -13, -13]])

In [24]:
arr/arr1

array([[0.07142857, 0.13333333, 0.1875    ],
       [0.23529412, 0.27777778, 0.31578947],
       [0.35      , 0.38095238, 0.40909091]])

In [25]:
np.divide(arr,arr1)

array([[0.07142857, 0.13333333, 0.1875    ],
       [0.23529412, 0.27777778, 0.31578947],
       [0.35      , 0.38095238, 0.40909091]])

In [26]:
arr*arr1

array([[ 14,  30,  48],
       [ 68,  90, 114],
       [140, 168, 198]])

In [27]:
np.multiply(arr,arr1)

array([[ 14,  30,  48],
       [ 68,  90, 114],
       [140, 168, 198]])

In [28]:
arr @ arr1

array([[108, 114, 120],
       [261, 276, 291],
       [414, 438, 462]])

In [29]:
arr.dot(arr1)

array([[108, 114, 120],
       [261, 276, 291],
       [414, 438, 462]])

In [30]:
arr.max()

9

In [31]:
arr1.max()

22

In [32]:
arr1.argmax()

8

In [33]:
arr1.max(axis =0)

array([20, 21, 22])

In [34]:
print(arr1)

[[14 15 16]
 [17 18 19]
 [20 21 22]]


In [35]:
arr1.max(axis = 1)

array([16, 19, 22])

In [36]:
arr1.min()

14

In [37]:
arr1.argmin()

0

In [38]:
np.sum(arr1)

162

In [39]:
print(arr1)

[[14 15 16]
 [17 18 19]
 [20 21 22]]


In [40]:
np.sum(arr1,1)

array([45, 54, 63])

In [41]:
np.mean(arr1)

18.0

In [42]:
np.sqrt(arr1)

array([[3.74165739, 3.87298335, 4.        ],
       [4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576]])

In [43]:
np.std(arr1)

2.581988897471611

In [44]:
np.exp(arr1)

array([[1.20260428e+06, 3.26901737e+06, 8.88611052e+06],
       [2.41549528e+07, 6.56599691e+07, 1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09]])

In [45]:
np.log(arr1)

array([[2.63905733, 2.7080502 , 2.77258872],
       [2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245]])

In [46]:
np.log(arr1)

array([[2.63905733, 2.7080502 , 2.77258872],
       [2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245]])

In [47]:
list = [1,2]
list1 = [3,4]
list + list1

[1, 2, 3, 4]

In [49]:
np.concatenate((arr,arr1),1)

array([[ 1,  2,  3, 14, 15, 16],
       [ 4,  5,  6, 17, 18, 19],
       [ 7,  8,  9, 20, 21, 22]])

In [52]:
np.hstack((arr,arr1))

array([[ 1,  2,  3, 14, 15, 16],
       [ 4,  5,  6, 17, 18, 19],
       [ 7,  8,  9, 20, 21, 22]])

In [3]:
arr2 = np.arange(1,17)
print(arr2)
list3 = np.split(arr2, [1,4,7,15])
print(list3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[array([1]), array([2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15]), array([16])]


In [90]:
type(list3
    )

list

In [4]:
list3[0]

array([1])

In [70]:
type(list3[0])

numpy.ndarray